### ISSUE TITLE
Theme-breaking update

### ISSUE THREAD

**Issue by AnubisNekhet** [BlueFalconHD/anki#2]
The latest Anki (and subsequently Recolor) update has added new variables for theming.

**Comment by BlueFalconHD** [comment]
I am very busy at the moment. Do you think you could help?

**Comment by nonetrix** [comment]
Same here seems fairly minor though
![image](https://user-images.githubusercontent.com/45698918/219537567-d47fe4a7-581c-4d0c-a0a2-f8c5a369f291.png)

**Comment by nonetrix** [comment]
Would anyone mind telling me where I can find documentation or something similar to attempt to fix it?

**Comment by BlueFalconHD** [comment]
Fixed.
// cc: @nonetrix
